# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech_recognition',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='speech_recognition',
            name='audioFile',
            field=models.FileField(upload_to='audios/%Y/%m/%d/'),
        ),
    ]
