# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SR', '0002_auto_20170616_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech_recognition',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
