# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR', '0003_auto_20170616_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech_recognition',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
