# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR', '0004_speech_recognition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech_recognition',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
