# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SR', '0006_auto_20170628_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech_recognition',
            name='audioFile',
            field=models.FileField(upload_to='audios/%Y/%m/%d/'),
        ),
    ]
